# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:09:30+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    A_RECORD = 'A_RECORD'
    CHILD_ABUSE = 'CHILD_ABUSE'
    CONTENT = 'CONTENT'
    FRAUD_WIRE = 'FRAUD_WIRE'
    IP_BLOCK = 'IP_BLOCK'
    MALWARE = 'MALWARE'
    NETWORK_ABUSE = 'NETWORK_ABUSE'
    PHISHING = 'PHISHING'
    SPAM = 'SPAM'


class AbuseTicket(BaseModel):
    closed: bool = Field(..., description='Is this abuse ticket closed?')
    closedAt: str = Field(..., description='The date the abuse ticket was closed')
    createdAt: str = Field(..., description='The date the abuse ticket was created')
    domainIp: str = Field(
        ..., description='The domain or IP the suspected abuse was reported against'
    )
    reporter: str = Field(
        ..., description='The shopper id of the person who reported the suspected abuse'
    )
    source: str = Field(
        ..., description='The single URL or IP the suspected abuse was reported against'
    )
    target: str = Field(..., description='The company the suspected abuse is targeting')
    ticketId: str = Field(..., description='Abuse ticket ID')
    type: Type = Field(..., description='The type of abuse being reported')


class AbuseTicketCreate(BaseModel):
    info: Optional[str] = Field(
        None,
        description='Additional information that may assist the abuse investigator. ie: server logs or email headers/body for SPAM',
    )
    infoUrl: Optional[str] = Field(
        None,
        description='Reporter URL if housing additional information that may assist the abuse investigator',
    )
    intentional: Optional[bool] = Field(
        False,
        description='Do you believe this is intentional abuse by the domain holder?',
    )
    proxy: Optional[str] = Field(
        None,
        description='The Proxy information required to view the abuse being reported. ie: Specific IP used, or country of IP viewing from',
    )
    source: Optional[str] = Field(
        None,
        description='The URL or IP where live abuse content is located at. ie: https://www.example.com/bad_stuff/bad.php',
    )
    target: Optional[str] = Field(
        None,
        description='The brand/company the abuse is targeting. ie: brand name/bank name',
    )
    type: Optional[Type] = Field(None, description='The type of abuse being reported.')


class AbuseTicketId(BaseModel):
    u_number: Optional[str] = Field(None, description='Abuse ticket ID')


class ErrorField(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    message: Optional[str] = Field(
        None,
        description='Human-readable, English description of the problem with the contents of the field',
    )
    path: str = Field(
        ...,
        description='1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error',
    )
    pathRelated: Optional[str] = Field(
        None,
        description='JSONPath referring to the field on the object referenced by `path` containing an error',
    )


class Pagination(BaseModel):
    first: Optional[str] = Field(
        None, description='Optional link to first list of results'
    )
    last: Optional[str] = Field(
        None, description='Optional link to last list of results'
    )
    next: Optional[str] = Field(
        None, description='Optional link to next list of results'
    )
    previous: Optional[str] = Field(
        None, description='Optional link to previous list of results'
    )
    total: Optional[int] = Field(None, description='Number of records available')


class AbuseTicketList(BaseModel):
    pagination: Optional[Pagination] = None
    ticketIds: List[str] = Field(
        ..., description='A list of abuse ticket ids originated by this reporter.'
    )


class Error(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    fields: Optional[List[ErrorField]] = Field(
        None,
        description='List of the specific fields, and the errors found with their contents',
    )
    message: Optional[str] = Field(
        None, description='Human-readable, English description of the error'
    )
    stack: Optional[List[str]] = Field(
        None,
        description='Stack trace indicating where the error occurred.<br/>\nNOTE: This attribute <strong>MAY</strong> be included for Development and Test environments.\nHowever, it <strong>MUST NOT</strong> be exposed from OTE nor Production systems.',
    )
